#include "MKL25Z4.h" 
#include "led.h"

void RedLED(int input) {
	int PTD_IN  = (input & 0b11000000) >> 6;
	int PTA_IN  = (input & 0b00110000) >> 4;
	int PTC_IN1 = (input & 0b00001100) >> 2;
	int PTC_IN2 = (input & 0b00000011);
	
	PTD->PDOR &= ~(MASK(PTD6_PIN)|MASK(PTD7_PIN));
	PTD->PDOR |= PTD_IN << 6;
	PTA->PDOR &= ~(MASK(PTA16_PIN) | MASK(PTA17_PIN));
	PTA->PDOR |= PTA_IN << 16;
	PTC->PDOR &= ~(MASK(PTC16_PIN) | MASK(PTC17_PIN) | MASK(PTC13_PIN) | MASK(PTC12_PIN));
	PTC->PDOR |= (PTC_IN1 << 16);
	PTC->PDOR |= (PTC_IN2 << 12);
}

void GreenLED(int input){
	int PTB_IN = input & 0x0F;
	int PTE_IN = (input & 0xF0) >> 4;
	
	PTB->PDOR &= ~(MASK(PTB8_PIN)|MASK(PTB9_PIN)|MASK(PTB10_PIN)|MASK(PTB11_PIN));
	PTB->PDOR |= PTB_IN << 8;
	PTE->PDOR &= ~(MASK(PTE2_PIN)|MASK(PTE3_PIN)|MASK(PTE4_PIN)|MASK(PTE5_PIN));
	PTE->PDOR |= PTE_IN << 2;
}

void InitLed(void) {
	// Configure MUX settings to make pins to ALT3: TPM1_CH0 and TPM1_CH1
  // Enable Clock to PORTPTE->PDOR = MASK(PTE2_PIN);B, PORTD, PORTA, PORTC and PORTE
	SIM->SCGC5 |= ((SIM_SCGC5_PORTB_MASK) | (SIM_SCGC5_PORTE_MASK) | (SIM_SCGC5_PORTD_MASK) | (SIM_SCGC5_PORTA_MASK) | (SIM_SCGC5_PORTC_MASK));
  
  // Configure Mode 1 for PWM pin operation
  // Alternative 1 GPIO
  PORTB->PCR[PTB8_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB8_PIN] |= PORT_PCR_MUX(1);
  PORTB->PCR[PTB9_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB9_PIN] |= PORT_PCR_MUX(1);
	PORTB->PCR[PTB10_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB10_PIN] |= PORT_PCR_MUX(1);
	PORTB->PCR[PTB11_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB11_PIN] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[PTE2_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTE->PCR[PTE2_PIN] |= PORT_PCR_MUX(1);
	PORTE->PCR[PTE3_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTE->PCR[PTE3_PIN] |= PORT_PCR_MUX(1);
	PORTE->PCR[PTE4_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTE->PCR[PTE4_PIN] |= PORT_PCR_MUX(1);
	PORTE->PCR[PTE5_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTE->PCR[PTE5_PIN] |= PORT_PCR_MUX(1);

	
	PORTD->PCR[PTD7_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTD->PCR[PTD7_PIN] |= PORT_PCR_MUX(1);
	PORTD->PCR[PTD6_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTD->PCR[PTD6_PIN] |= PORT_PCR_MUX(1);
	
	PORTA->PCR[PTA17_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTA->PCR[PTA17_PIN] |= PORT_PCR_MUX(1);
	PORTA->PCR[PTA16_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTA->PCR[PTA16_PIN] |= PORT_PCR_MUX(1);
	
	PORTC->PCR[PTC17_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTC->PCR[PTC17_PIN] |= PORT_PCR_MUX(1);
	PORTC->PCR[PTC16_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTC->PCR[PTC16_PIN] |= PORT_PCR_MUX(1);
	PORTC->PCR[PTC13_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTC->PCR[PTC13_PIN] |= PORT_PCR_MUX(1);
	PORTC->PCR[PTC12_PIN] &= ~PORT_PCR_MUX_MASK;
  PORTC->PCR[PTC12_PIN] |= PORT_PCR_MUX(1);
	
	PTB->PDDR |= (MASK(PTB8_PIN)|MASK(PTB9_PIN)|MASK(PTB10_PIN)|MASK(PTB11_PIN));
	PTE->PDDR |= (MASK(PTE2_PIN)|MASK(PTE3_PIN)|MASK(PTE4_PIN)|MASK(PTE5_PIN));
	PTA->PDDR |= (MASK(PTA17_PIN)|MASK(PTA16_PIN));
	PTD->PDDR |= (MASK(PTD7_PIN)|MASK(PTD6_PIN));
	PTC->PDDR |= (MASK(PTC17_PIN)|MASK(PTC16_PIN)|MASK(PTC13_PIN)|MASK(PTC12_PIN));
}
